services:
  # MinIo Object Storage

  minio:
    image: minio/minio:latest
    env_file:
     - ./env/.env.admin
    container_name: lakehouse-minio
    restart: always
    ports:
      - "${MINIO_API_PORT:-9000}:9000"   # API
      - "${MINIO_CONSOLE_PORT:-9001}:9001" # Console UI

    #environment:
    #  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    #  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - ./data/minio-data:/data # this indicates that any data uploaded to minio will be stored in the /data directory
    command: server /data --console-address ":9001" # this provides a separate port for manain buckets and uploadin and download objects (9001)

    networks:
      - lakehouse-net

  spark-master:
     build: .
     container_name: spark-master
     restart: unless-stopped

     ports: 
       - "7077:7077"
       - "8081:8080" 

     environment:
        - SPARK_MASTER_HOST=spark-master
        - SPARK_MASTER_PORT=7077
        - SPARK_MASTER_WEBUI_PORT=8080
        

     command: >
       /opt/spark/bin/spark-class
       org.apache.spark.deploy.master.Master


     networks:
       - lakehouse-net



  spark-worker:
    build: .
    container_name: spark-worker
    restart: unless-stopped

    depends_on:
      - spark-master

    ports:
      - "8082:8081"

    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      
      - SPARK_DAEMON_MEMORY=1G
      - SPARK_MASTER=spark://spark-master:7077

    command: >
       /opt/spark/bin/spark-class
       org.apache.spark.deploy.worker.Worker
       spark://spark-master:7077

      
    networks:
      - lakehouse-net

networks:
  lakehouse-net:
    name: lakehouse-net
    driver: bridge

    

    