services:

  ingestion-job:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: ingestion-job
    hostname: spark-test-ingestion

    env_file:
      - ./env/.env.ingestion


    environment:
      PIPELINE_STAGE: ingestion
      SPARK_DRIVER_HOST: spark-test-ingestion

    ports:
      - "34567:34567"
      - "34568:34568"

    
    volumes:

      - ./src:/opt/spark-app/src
      - ./configs:/opt/spark-app/configs
      - ./env:/opt/spark-app/env
    
      - ./data/logs/:/opt/spark-app/data/logs


    command:  tail -f /dev/null


    networks:
      lakehouse-net:
        aliases:
          - spark-test-ingestion


networks:
  lakehouse-net:
    external: true
    name: lakehouse-net